# Generated by Django 5.2.11 on 2026-03-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_sigup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_sigup',
            name='Locality',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_sigup',
            name='Address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_sigup',
            name='Status',
            field=models.CharField(default='waiting', max_length=100),
        ),
    ]
